# Based on the following mkdocs.yml's:
# - https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
# - https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/mkdocs.yml

site_name: The Internals of Apache Spark
site_url: https://books.japila.pl/apache-spark-internals
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Apache Spark

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_name: apache-spark-internals
repo_url: https://github.com/japila-books/apache-spark-internals
edit_uri: edit/mkdocs-material/docs/

copyright: |
  Copyright &copy; 2020 <a href="https://twitter.com/jaceklaskowski" target="_blank" rel="noopener">Jacek Laskowski</a>

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  # the following two lines don't seem to work on ReadTheDocs
  # https://github.com/readthedocs/readthedocs.org/issues/6889
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date:
      enabled_if_env: CI
  - awesome-pages
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
  spark:
    version: 3.0.1
  hadoop:
    version: 2.7.4

google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

nav:
  - Home:
    - Welcome: index.md
    - Overview: overview.md
    - SparkEnv: SparkEnv.md
    - SparkConf: SparkConf.md
    - SparkContext:
      - SparkContext: SparkContext.md
      - Creating SparkContext: spark-SparkContext-creating-instance-internals.md
    - Logging: spark-logging.md
    - Core:
      - BroadcastManager: core/BroadcastManager.md
      - BroadcastFactory: core/BroadcastFactory.md
      - TorrentBroadcastFactory: core/TorrentBroadcastFactory.md
      - TorrentBroadcast: core/TorrentBroadcast.md
      - ContextCleaner: core/ContextCleaner.md
      - CleanerListener: core/CleanerListener.md
      - BlockFetchingListener: core/BlockFetchingListener.md
      - RetryingBlockFetcher: core/RetryingBlockFetcher.md
      - BlockFetchStarter: core/BlockFetchStarter.md
      - AppStatusListener: core/AppStatusListener.md
      - AppStatusStore: core/AppStatusStore.md
      - KVStore: core/KVStore.md
      - ElementTrackingStore: core/ElementTrackingStore.md
      - InMemoryStore: core/InMemoryStore.md
      - LevelDB: core/LevelDB.md
    - Scheduler:
      - Spark Scheduler: scheduler/index.md
      - DAGScheduler: scheduler/DAGScheduler.md
      - DAGSchedulerEvent: scheduler/DAGSchedulerEvent.md
      - DAGSchedulerEventProcessLoop: scheduler/DAGSchedulerEventProcessLoop.md
      - Stage: scheduler/Stage.md
      - ResultStage: scheduler/ResultStage.md
      - ShuffleMapStage: scheduler/ShuffleMapStage.md
      - MapOutputTracker: scheduler/MapOutputTracker.md
      - MapOutputTrackerMaster: scheduler/MapOutputTrackerMaster.md
      - ShuffleStatus: scheduler/ShuffleStatus.md
      - MapOutputTrackerMasterEndpoint: scheduler/MapOutputTrackerMasterEndpoint.md
      - MapOutputTrackerWorker: scheduler/MapOutputTrackerWorker.md
      - StageInfo: scheduler/spark-scheduler-StageInfo.md
      - JobListener: scheduler/spark-scheduler-JobListener.md
      - JobWaiter: scheduler/spark-scheduler-JobWaiter.md
      - TaskScheduler: scheduler/TaskScheduler.md
      - TaskSchedulerImpl: scheduler/TaskSchedulerImpl.md
      - SchedulerBackend: scheduler/SchedulerBackend.md
      - CoarseGrainedSchedulerBackend: scheduler/CoarseGrainedSchedulerBackend.md
      - DriverEndpoint: scheduler/CoarseGrainedSchedulerBackend-DriverEndpoint.md
      - Task: scheduler/Task.md
      - ShuffleMapTask: scheduler/ShuffleMapTask.md
      - ResultTask: scheduler/ResultTask.md
      - TaskSet: scheduler/TaskSet.md
      - TaskSetManager: scheduler/TaskSetManager.md
      - ActiveJob: scheduler/ActiveJob.md
      - SchedulableBuilder: scheduler/SchedulableBuilder.md
      - FIFOSchedulableBuilder: scheduler/FIFOSchedulableBuilder.md
      - FairSchedulableBuilder: scheduler/FairSchedulableBuilder.md
      - Schedulable: scheduler/Schedulable.md
      - Pool: scheduler/Pool.md
      - SchedulingMode: scheduler/SchedulingMode.md
      - TaskInfo: scheduler/TaskInfo.md
      - MapStatus: scheduler/MapStatus.md
      - TaskDescription: scheduler/TaskDescription.md
      - TaskResultGetter: scheduler/TaskResultGetter.md
      - TaskContext: scheduler/TaskContext.md
      - BarrierTaskContext: scheduler/BarrierTaskContext.md
      - TaskContextImpl: scheduler/TaskContextImpl.md
      - TaskResult: scheduler/TaskResult.md
      - TaskSetBlacklist: scheduler/TaskSetBlacklist.md
      - OutputCommitCoordinator: scheduler/OutputCommitCoordinator.md
      - TaskLocation: scheduler/TaskLocation.md
      - ExternalClusterManager: scheduler/ExternalClusterManager.md
      - LiveListenerBus: scheduler/LiveListenerBus.md
    - RPC:
      - RPC System: rpc/index.md
      - RpcEnv: rpc/RpcEnv.md
      - NettyRpcEnv: rpc/NettyRpcEnv.md
      - NettyStreamManager: rpc/NettyStreamManager.md
      - RpcEnvConfig: rpc/RpcEnvConfig.md
      - RpcEndpoint: rpc/RpcEndpoint.md
      - RpcEndpointRef: rpc/RpcEndpointRef.md
      - RpcAddress: rpc/RpcAddress.md
      - RpcEndpointAddress: rpc/RpcEndpointAddress.md
      - RpcEnvFactory: rpc/RpcEnvFactory.md
      - NettyRpcEnvFactory: rpc/NettyRpcEnvFactory.md
      - RpcEnvFileServer: rpc/RpcEnvFileServer.md
      - spark-rpc-netty: rpc/spark-rpc-netty.md
      - RpcUtils: rpc/RpcUtils.md
    - Memory:
      - Memory System: memory/index.md
      - MemoryManager: memory/MemoryManager.md
      - StaticMemoryManager: memory/StaticMemoryManager.md
      - UnifiedMemoryManager: memory/UnifiedMemoryManager.md
      - MemoryPool: memory/MemoryPool.md
      - ExecutionMemoryPool: memory/ExecutionMemoryPool.md
      - StorageMemoryPool: memory/StorageMemoryPool.md
      - TaskMemoryManager: memory/TaskMemoryManager.md
      - MemoryConsumer: memory/MemoryConsumer.md
      - BytesToBytesMap: memory/BytesToBytesMap.md
      - UnsafeSorterSpillReader: memory/UnsafeSorterSpillReader.md
      - UnsafeExternalSorter: memory/UnsafeExternalSorter.md
      - UnsafeInMemorySorter: memory/UnsafeInMemorySorter.md
      - UnsafeSorterSpillWriter: memory/UnsafeSorterSpillWriter.md
    - Storage:
      - BlockManager: storage/BlockManager.md
      - BlockManagerId: storage/BlockManagerId.md
      - BlockManagerInfo: storage/BlockManagerInfo.md
      - BlockManagerMaster: storage/BlockManagerMaster.md
      - BlockManagerMasterEndpoint: storage/BlockManagerMasterEndpoint.md
      - BlockManagerSlaveEndpoint: storage/BlockManagerSlaveEndpoint.md
      - BlockId: storage/BlockId.md
      - BlockDataManager: storage/BlockDataManager.md
      - DiskStore: storage/DiskStore.md
      - DiskBlockManager: storage/DiskBlockManager.md
      - MemoryStore: storage/MemoryStore.md
      - BlockEvictionHandler: storage/BlockEvictionHandler.md
      - BlockData: storage/BlockData.md
      - BlockInfoManager: storage/BlockInfoManager.md
      - BlockInfo: storage/BlockInfo.md
      - DiskBlockObjectWriter: storage/DiskBlockObjectWriter.md
      - BlockManagerSource: storage/BlockManagerSource.md
      - ShuffleMetricsSource: storage/ShuffleMetricsSource.md
      - ShuffleClient: storage/ShuffleClient.md
      - BlockTransferService: storage/BlockTransferService.md
      - NettyBlockTransferService: storage/NettyBlockTransferService.md
      - NettyBlockRpcServer: storage/NettyBlockRpcServer.md
      - ExternalShuffleClient: storage/ExternalShuffleClient.md
      - OneForOneBlockFetcher: storage/OneForOneBlockFetcher.md
      - ShuffleBlockFetcherIterator: storage/ShuffleBlockFetcherIterator.md
      - RDDInfo: storage/RDDInfo.md
      - StorageLevel: storage/StorageLevel.md
      - StorageStatus: storage/StorageStatus.md
    - Serialization:
      - Serialization System: serializer/index.md
      - SerializerManager: serializer/SerializerManager.md
      - Serializer: serializer/Serializer.md
      - SerializerInstance: serializer/SerializerInstance.md
      - SerializationStream: serializer/SerializationStream.md
      - DeserializationStream: serializer/DeserializationStream.md
    - Shuffle:
      - Shuffle System: shuffle/index.md
      - ShuffleManager: shuffle/ShuffleManager.md
      - SortShuffleManager: shuffle/SortShuffleManager.md
      - ShuffleHandle: shuffle/ShuffleHandle.md
      - BaseShuffleHandle: shuffle/BaseShuffleHandle.md
      - BypassMergeSortShuffleHandle: shuffle/BypassMergeSortShuffleHandle.md
      - SerializedShuffleHandle: shuffle/SerializedShuffleHandle.md
      - ShuffleReader: shuffle/ShuffleReader.md
      - BlockStoreShuffleReader: shuffle/BlockStoreShuffleReader.md
      - ShuffleWriter: shuffle/ShuffleWriter.md
      - BypassMergeSortShuffleWriter: shuffle/BypassMergeSortShuffleWriter.md
      - SortShuffleWriter: shuffle/SortShuffleWriter.md
      - UnsafeShuffleWriter: shuffle/UnsafeShuffleWriter.md
      - ShuffleExternalSorter: shuffle/ShuffleExternalSorter.md
      - ShuffleInMemorySorter: shuffle/ShuffleInMemorySorter.md
      - ShuffleBlockResolver: shuffle/ShuffleBlockResolver.md
      - IndexShuffleBlockResolver: shuffle/IndexShuffleBlockResolver.md
      - FetchFailedException: shuffle/FetchFailedException.md
      - Spillable: shuffle/Spillable.md
      - ExternalAppendOnlyMap: shuffle/ExternalAppendOnlyMap.md
      - ExternalSorter: shuffle/ExternalSorter.md
  - Tools:
    - spark-shell: tools/spark-shell.md
  - RDD:
    - Resilient Distributed Dataset: rdd/index.md
    - RDD: rdd/RDD.md
    - RDDs:
      - CoGroupedRDD: rdd/spark-rdd-CoGroupedRDD.md
      - HadoopRDD: rdd/spark-rdd-HadoopRDD.md
      - MapPartitionsRDD: rdd/spark-rdd-MapPartitionsRDD.md
      - NewHadoopRDD: rdd/spark-rdd-NewHadoopRDD.md
      - OrderedRDDFunctions: rdd/spark-rdd-OrderedRDDFunctions.md
      - ParallelCollectionRDD: rdd/spark-rdd-ParallelCollectionRDD.md
      - CheckpointRDD: rdd/CheckpointRDD.md
      - ReliableCheckpointRDD: rdd/ReliableCheckpointRDD.md
      - ShuffledRDD: rdd/ShuffledRDD.md
      - SubtractedRDD: rdd/spark-rdd-SubtractedRDD.md
    - Operators:
      - Operators: rdd/spark-rdd-operations.md
      - Transformations: rdd/spark-rdd-transformations.md
      - PairRDDFunctions: rdd/PairRDDFunctions.md
      - Actions: rdd/spark-rdd-actions.md
    - Partitioner: rdd/Partitioner.md
    - RDD Lineage: rdd/spark-rdd-lineage.md
    - Caching and Persistence: rdd/spark-rdd-caching.md
    - Partitions and Partitioning: rdd/spark-rdd-partitions.md
    - Partition: rdd/spark-rdd-Partition.md
    - RDDCheckpointData: rdd/RDDCheckpointData.md
    - LocalRDDCheckpointData: rdd/LocalRDDCheckpointData.md
    - ReliableRDDCheckpointData: rdd/ReliableRDDCheckpointData.md
    - Shuffling: rdd/spark-rdd-shuffle.md
    - Dependencies: rdd/spark-rdd-Dependency.md
    - NarrowDependency: rdd/spark-rdd-NarrowDependency.md
    - ShuffleDependency: rdd/ShuffleDependency.md
    - Aggregator: rdd/Aggregator.md
    - Partitioners:
      - HashPartitioner: rdd/HashPartitioner.md
      - RangePartitioner: rdd/RangePartitioner.md
  - Metrics:
    - Spark Metrics: metrics/index.md
    - Configuration Properties: metrics/configuration-properties.md
    - MetricsSystem: metrics/MetricsSystem.md
    - MetricsConfig: metrics/MetricsConfig.md
    - Source: metrics/Source.md
    - Sink: metrics/Sink.md
    - Sources:
      - JvmSource: metrics/JvmSource.md
      - DAGSchedulerSource: metrics/DAGSchedulerSource.md
    - Sinks:
      - MetricsServlet: metrics/MetricsServlet.md
  - Demos:
    - DiskBlockManager and Block Data: demo/diskblockmanager-and-block-data.md