# Based on the following mkdocs.yml's:
# - https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
# - https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/mkdocs.yml

site_name: The Internals of Apache Spark
site_url: https://books.japila.pl/apache-spark-internals
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Apache Spark

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_name: apache-spark-internals
repo_url: https://github.com/japila-books/apache-spark-internals
edit_uri: edit/mkdocs-material/docs/

copyright: |
  Copyright &copy; 2020 <a href="https://twitter.com/jaceklaskowski" target="_blank" rel="noopener">Jacek Laskowski</a>

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  # the following two lines don't seem to work on ReadTheDocs
  # https://github.com/readthedocs/readthedocs.org/issues/6889
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date:
      enabled_if_env: CI
  - awesome-pages
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
  spark:
    version: 3.0.1
  hadoop:
    version: 2.7.4

google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

nav:
  - Home:
    - Welcome: index.md
    - Overview: overview.md
  - RDD:
    - Resilient Distributed Dataset: rdd/index.md
    - RDD: rdd/RDD.md
    - RDDs:
      - CoGroupedRDD: rdd/spark-rdd-CoGroupedRDD.md
      - HadoopRDD: rdd/spark-rdd-HadoopRDD.md
      - MapPartitionsRDD: rdd/spark-rdd-MapPartitionsRDD.md
      - NewHadoopRDD: rdd/spark-rdd-NewHadoopRDD.md
      - OrderedRDDFunctions: rdd/spark-rdd-OrderedRDDFunctions.md
      - ParallelCollectionRDD: rdd/spark-rdd-ParallelCollectionRDD.md
      - CheckpointRDD: rdd/CheckpointRDD.md
      - ReliableCheckpointRDD: rdd/ReliableCheckpointRDD.md
      - ShuffledRDD: rdd/ShuffledRDD.md
      - SubtractedRDD: rdd/spark-rdd-SubtractedRDD.md
    - Operators:
      - Operators: rdd/spark-rdd-operations.md
      - Transformations: rdd/spark-rdd-transformations.md
      - PairRDDFunctions: rdd/PairRDDFunctions.md
      - Actions: rdd/spark-rdd-actions.md
    - Partitioner: rdd/Partitioner.md
    - RDD Lineage: rdd/spark-rdd-lineage.md
    - Caching and Persistence: rdd/spark-rdd-caching.md
    - Partitions and Partitioning: rdd/spark-rdd-partitions.md
    - Partition: rdd/spark-rdd-Partition.md
    - RDDCheckpointData: rdd/RDDCheckpointData.md
    - LocalRDDCheckpointData: rdd/LocalRDDCheckpointData.md
    - ReliableRDDCheckpointData: rdd/ReliableRDDCheckpointData.md
    - Shuffling: rdd/spark-rdd-shuffle.md
    - Dependencies: rdd/spark-rdd-Dependency.md
    - NarrowDependency: rdd/spark-rdd-NarrowDependency.md
    - ShuffleDependency: rdd/ShuffleDependency.md
    - Aggregator: rdd/Aggregator.md
    - Partitioners:
      - HashPartitioner: rdd/HashPartitioner.md
      - RangePartitioner: rdd/RangePartitioner.md
  - Metrics:
    - Spark Metrics: metrics/index.md
    - Configuration Properties: metrics/configuration-properties.md
    - MetricsSystem: metrics/MetricsSystem.md
    - MetricsConfig: metrics/MetricsConfig.md
    - Source: metrics/Source.md
    - Sink: metrics/Sink.md
    - Sources:
      - JvmSource: metrics/JvmSource.md
      - DAGSchedulerSource: metrics/DAGSchedulerSource.md
    - Sinks:
      - MetricsServlet: metrics/MetricsServlet.md
